### ISSUE TITLE
Static code

### ISSUE THREAD

**Issue by dcswitzer** [HAN-ASD-DT/elm-assignment-Dewinster#2]
https://github.com/HAN-ASD-DT/elm-assignment-Dewinster/blob/60331fc10f661cc8e11a61af86c7dcca673b80f7/src/Assignment/Two.elm#L53-L56

Looks like your else statement won't work correctly if you swap first and second.
Your code is correct for the testcase -> [1,6] [3,7] should be Just [3,6]
But if you swap first and second it won't work -> [3,7] [1,6] results in tou case to [1,7]

**Comment by dvberkel** [comment]
I was going to say the same

**Comment by Dewinster** [comment]
[Solved](https://github.com/HAN-ASD-DT/elm-assignment-Dewinster/commit/262cbaef82e1550c763e1db539de6546380b0b8b)
